version: "3.7"

services:
  app:
    image: ashrhmn/go-logger
    ports:
      - "4000:4000" # Log UI
    restart: on-failure
    environment:
      - MONGO_URI=mongodb://db:27017
      - RMQ_URL=amqp://guest:guest@rmq:5672
    depends_on:
      - db
      - rmq
  db:
    image: mongo
  rmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # RMQ UI (optional)
      - "5672:5672" # RMQ (Post log messages here)
